export interface DtcDefinition {
  code: string;
  category: 'Powertrain' | 'Chassis' | 'Body' | 'Network';
  system: string;
  title: string;
  description: string;
  severity: 'Critical' | 'Moderate' | 'Minor' | 'Info';
  symptoms: string[];
  possibleCauses: string[];
  civicSpecificNotes?: string;
}

export const HONDA_DTC_DATABASE: Record<string, DtcDefinition> = {
  // Fuel & Air Metering
  P0171: {
    code: 'P0171',
    category: 'Powertrain',
    system: 'Fuel & Air Metering',
    title: 'System Too Lean (Bank 1)',
    description: 'The engine ECU has detected that the air-fuel mixture is too lean (too much air or not enough fuel), exceeding the positive fuel trim limit (+15% to +25%).',
    severity: 'Moderate',
    symptoms: ['Rough idle', 'Hesitation during acceleration', 'Reduced fuel economy', 'May be pending before CEL illuminates'],
    possibleCauses: ['Dirty or contaminated Mass Air Flow (MAF) sensor', 'Vacuum leak downstream of MAF (cracked intake boot)', 'Low fuel pressure / clogged fuel injector', 'Exhaust leak before upstream O2 sensor'],
    civicSpecificNotes: 'Common on 2012-2015 Civics due to hairline cracks in the rubber intake air duct between the airbox and throttle body.',
  },
  P0172: {
    code: 'P0172',
    category: 'Powertrain',
    system: 'Fuel & Air Metering',
    title: 'System Too Rich (Bank 1)',
    description: 'The engine ECU detected excessive fuel or insufficient air, driving negative fuel trims past limits.',
    severity: 'Moderate',
    symptoms: ['Strong fuel smell from exhaust', 'Black exhaust smoke under load', 'Sluggish acceleration', 'Lower MPG'],
    possibleCauses: ['Faulty or contaminated MAF sensor reading high', 'Leaking fuel injector', 'Excessive fuel pressure', 'Stuck open EVAP purge valve'],
  },
  P0101: {
    code: 'P0101',
    category: 'Powertrain',
    system: 'Fuel & Air Metering',
    title: 'Mass Air Flow (MAF) Circuit Range/Performance',
    description: 'MAF sensor signal is out of expected range compared to throttle position and engine RPM.',
    severity: 'Moderate',
    symptoms: ['Hesitation', 'Stalling when coming to a stop in neutral', 'Erratic idle'],
    possibleCauses: ['Dirty MAF sensor element', 'Air intake leak', 'Damaged MAF sensor wiring harness'],
  },
  P0128: {
    code: 'P0128',
    category: 'Powertrain',
    system: 'Cooling System',
    title: 'Coolant Thermostat (Coolant Temp Below Regulating Temp)',
    description: 'Engine coolant temperature has not reached normal operating temperature (approx 160°F–180°F) within a calculated time after starting.',
    severity: 'Minor',
    symptoms: ['Heater blows lukewarm air', 'Decreased fuel economy (engine stays in warm-up enrichment)', 'Oil takes longer to burn off condensation'],
    possibleCauses: ['Thermostat stuck open or opening prematurely', 'Faulty Engine Coolant Temperature (ECT) sensor', 'Low coolant level'],
    civicSpecificNotes: 'Directly impacts the Oil Life Calculator and fuel trim efficiency because the engine remains in open-loop/warmup mode.',
  },
  P0133: {
    code: 'P0133',
    category: 'Powertrain',
    system: 'Fuel & Air Metering',
    title: 'O2 Sensor Circuit Slow Response (Bank 1 Sensor 1)',
    description: 'Upstream wideband Air/Fuel sensor takes too long to switch between rich and lean signals during transient throttle.',
    severity: 'Moderate',
    symptoms: ['Slight hesitation', 'Gradual degradation of MPG', 'Often exists as a PENDING code for hundreds of miles before CEL triggers'],
    possibleCauses: ['Aging or contaminated primary A/F ratio sensor', 'Exhaust manifold crack', 'Fuel contamination'],
  },
  P0135: {
    code: 'P0135',
    category: 'Powertrain',
    system: 'Fuel & Air Metering',
    title: 'O2 Sensor Heater Circuit (Bank 1 Sensor 1)',
    description: 'Electrical resistance fault in the internal heating element of the upstream air-fuel sensor.',
    severity: 'Moderate',
    symptoms: ['Delayed entry into closed-loop fuel control after cold start'],
    possibleCauses: ['Burned out heater element in primary O2 sensor', 'Blown O2 heater fuse in under-dash fuse box'],
  },

  // Ignition & Misfires
  P0300: {
    code: 'P0300',
    category: 'Powertrain',
    system: 'Ignition & Misfire',
    title: 'Random / Multiple Cylinder Misfire Detected',
    description: 'ECU crankshaft speed fluctuations indicate multiple cylinders are failing to ignite consistently.',
    severity: 'Critical',
    symptoms: ['Jerking / stumbling under load', 'Flashing Check Engine Light (signals catalytic converter damage risk)', 'Sulfur smell'],
    possibleCauses: ['Worn spark plugs', 'Low fuel delivery pressure', 'Major vacuum leak', 'Contaminated fuel'],
  },
  P0301: {
    code: 'P0301',
    category: 'Powertrain',
    system: 'Ignition & Misfire',
    title: 'Cylinder 1 Misfire Detected',
    description: 'Crankshaft sensor detected rotational deceleration during Cylinder 1 power stroke.',
    severity: 'Critical',
    symptoms: ['Engine vibration', 'Rough idle in neutral', 'Loss of acceleration in 1st/2nd gear'],
    possibleCauses: ['Failing ignition coil on Cyl 1', 'Worn NGK laser iridium spark plug', 'Clogged injector on Cyl 1', 'Valve adjustment required'],
  },
  P0302: {
    code: 'P0302',
    category: 'Powertrain',
    system: 'Ignition & Misfire',
    title: 'Cylinder 2 Misfire Detected',
    description: 'Crankshaft sensor detected rotational deceleration during Cylinder 2 power stroke.',
    severity: 'Critical',
    symptoms: ['Engine vibration', 'Hesitation', 'Power loss'],
    possibleCauses: ['Ignition coil 2', 'Spark plug gap', 'Fuel injector 2'],
  },
  P0303: {
    code: 'P0303',
    category: 'Powertrain',
    system: 'Ignition & Misfire',
    title: 'Cylinder 3 Misfire Detected',
    description: 'Crankshaft sensor detected rotational deceleration during Cylinder 3 power stroke.',
    severity: 'Critical',
    symptoms: ['Engine vibration', 'Hesitation', 'Power loss'],
    possibleCauses: ['Ignition coil 3', 'Spark plug gap', 'Fuel injector 3'],
  },
  P0304: {
    code: 'P0304',
    category: 'Powertrain',
    system: 'Ignition & Misfire',
    title: 'Cylinder 4 Misfire Detected',
    description: 'Crankshaft sensor detected rotational deceleration during Cylinder 4 power stroke.',
    severity: 'Critical',
    symptoms: ['Engine vibration', 'Hesitation', 'Power loss'],
    possibleCauses: ['Ignition coil 4', 'Spark plug gap', 'Fuel injector 4'],
  },

  // Emissions & EVAP
  P0420: {
    code: 'P0420',
    category: 'Powertrain',
    system: 'Emissions Control',
    title: 'Catalyst System Efficiency Below Threshold (Bank 1)',
    description: 'Downstream secondary O2 sensor switching frequency mirrors the upstream sensor, indicating the catalytic converter is not storing enough oxygen.',
    severity: 'Minor',
    symptoms: ['No noticeable driveability issue in most cases', 'Fails emissions inspection', 'Often stays as a pending code during highway drive cycles'],
    possibleCauses: ['Degraded catalytic converter substrate', 'Exhaust leak near secondary O2 sensor', 'Contamination from oil blowby or unburnt fuel'],
  },
  P0455: {
    code: 'P0455',
    category: 'Powertrain',
    system: 'Evaporative Emissions (EVAP)',
    title: 'EVAP System Large Leak Detected',
    description: 'The fuel tank vapor recovery system failed the engine vacuum pull-down test, indicating a large air leak.',
    severity: 'Minor',
    symptoms: ['"Check Fuel Cap" warning on dashboard i-MID screen', 'Faint fuel vapor odor near rear quarter panel'],
    possibleCauses: ['Loose, missing, or worn fuel filler cap gasket', 'Disconnected EVAP canister purge line', 'Defective EVAP canister vent valve'],
  },
  P0456: {
    code: 'P0456',
    category: 'Powertrain',
    system: 'Evaporative Emissions (EVAP)',
    title: 'EVAP System Very Small Leak Detected (0.020")',
    description: 'Minor pressure loss in fuel vapor system during overnight soak test.',
    severity: 'Minor',
    symptoms: ['No driveability symptoms', 'Intermittent pending code'],
    possibleCauses: ['Slightly dried fuel cap O-ring seal', 'Micro-crack in plastic EVAP vapor lines'],
  },
  P145C: {
    code: 'P145C',
    category: 'Powertrain',
    system: 'Honda Proprietary EVAP',
    title: 'EVAP Purge Flow Malfunction (Honda Specific)',
    description: 'Honda-specific diagnostic: MAP sensor did not register expected manifold pressure drop when EVAP purge solenoid opened.',
    severity: 'Minor',
    symptoms: ['Check engine light', 'Can trigger after refueling'],
    possibleCauses: ['Stuck closed EVAP purge control solenoid valve', 'Clogged vacuum purge port on throttle body'],
  },

  // VTEC & Engine Controls
  P2646: {
    code: 'P2646',
    category: 'Powertrain',
    system: 'Variable Valve Timing (i-VTEC)',
    title: 'VTEC Rocker Arm Oil Pressure Switch Circuit Low Voltage',
    description: 'When the ECU commanded i-VTEC high-lift cam transition at ~4,800 RPM, the VTEC oil pressure switch did not detect sufficient hydraulic oil pressure to lock the rocker arms.',
    severity: 'Moderate',
    symptoms: ['Engine stutters or hits a "wall" around 4,000–5,000 RPM (VTEC limp mode)', 'Car drives normally below 3,500 RPM'],
    possibleCauses: ['Low engine oil level', 'Clogged VTEC spool valve solenoid screen/filter gasket', 'Dirty or degraded engine oil', 'Faulty VTEC oil pressure switch'],
    civicSpecificNotes: 'Commonly triggered when engine oil is low or past its useful life, directly linking with your Oil Life Calculator!',
  },
  P0847: {
    code: 'P0847',
    category: 'Powertrain',
    system: 'Transmission',
    title: 'Transmission Fluid Pressure Sensor/Switch (3rd Clutch)',
    description: 'Circuit voltage low in transmission fluid pressure sensor.',
    severity: 'Minor',
    symptoms: ['May appear in ECU memory on certain scan tools'],
    possibleCauses: ['Corroded connector pin', 'Sensor replacement needed'],
  },
  U0100: {
    code: 'U0100',
    category: 'Network',
    system: 'CAN Communication',
    title: 'Lost Communication With ECM/PCM "A"',
    description: 'Data bus timeout between instrument cluster or ABS module and the Engine Control Module.',
    severity: 'Moderate',
    symptoms: ['Intermittent gauge flicker', 'ABS or VSA warning light'],
    possibleCauses: ['Low 12V battery voltage during cold crank', 'Loose OBD-II adapter connection'],
  },
};
